In [ ]:
import numpy as np

In [ ]:
#1-D Array

In [ ]:
a = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype


dtype('int64')

In [ ]:
b = np.array([2.3, 4.5])
b


array([2.3, 4.5])

In [ ]:
b.dtype

dtype('float64')

Multi-D Array

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

Initilaztion NumPy Array with Zero

In [ ]:
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
n1 = np.zeros((10,10))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Intilazing numpy with Same Number

In [ ]:
n3 = np.full((3,3),(5))
n3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
n4 = np.full((6,6), 23)
n4

array([[23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23]])

Initilization NumPy array within a range

In [ ]:
n5 = np.arange(1,51)
n5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
n6 = np.arange(0,51,10)
n6

array([ 0, 10, 20, 30, 40, 50])

initilization numpy array random numbers

In [ ]:
n7 = np.random.randint(1,101,10)
n7

array([ 47,  52,  31,  92, 100,  73,  13,  71,  67,  43])

Checking the shape of NumPy array

In [ ]:
n8 = np.array([[1,2,3], [4,5,6]])
n8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n8.shape

(2, 3)

In [ ]:
n8.shape = (3,2)
n8

array([[1, 2],
       [3, 4],
       [5, 6]])

Joining Of NumPy Array

In [ ]:
n9 = np.array([10,20,30])
n10 = np.array([40,50,60])

In [ ]:
np.vstack((n9,n10))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.hstack((n9,n10))

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.column_stack((n9,n10))

array([[10, 40],
       [20, 50],
       [30, 60]])

NumPy Intersection & Diffrence

In [ ]:
n11 = np.array([10,20,30,40,50,60])
n12 = np.array([50,60,70,80,90])

In [ ]:
np.intersect1d(n11,n12)

array([50, 60])

In [ ]:
np.setdiff1d(n11,n12)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n12,n11)

array([70, 80, 90])

Mathematics of NumPy Array

In [ ]:
n13 = np.array([10,20])
n14 = np.array([30,40])


In [ ]:
np.sum([n13,n14])

100

In [ ]:
np.sum([n13, n14], axis=0)

array([40, 60])

In [ ]:
np.sum([n13,n14], axis=1)

array([30, 70])

In [ ]:
n15 = np.array([10,20,30])

In [ ]:
n15+1

array([11, 21, 31])

In [ ]:
n15-1

array([ 9, 19, 29])

In [ ]:
n15*5

array([ 50, 100, 150])

In [ ]:
n15/3

array([ 3.33333333,  6.66666667, 10.        ])

In [ ]:
n16 = np.array([32,54,65,78,23,64,76,25,68,89,94,53])

In [ ]:
np.mean(n16)

60.083333333333336

In [ ]:
np.std(n16)

22.629104906931005

In [ ]:
np.median(n16)

64.5

In [ ]:
n17 = np.array([32,44,65])
n18 = np.array([45,76,22])

In [ ]:
n17.dot(n18)

6214

Save And Load NumPy

In [ ]:
n19 = np.array([12,34,56,324,6743,76,5634,64,7534,564,35])
np.save('final_numpy_array', n19)

In [ ]:
n20 = np.load('/content/final_numpy_array.npy')
n20

array([  12,   34,   56,  324, 6743,   76, 5634,   64, 7534,  564,   35])